// THIS IS A CODE FOR EDGE TRIGGERING INTERRUPT USING ASSEMBLY LANGUAGE

ORG 0000H
		LJMP MAIN   //LONG JUMP USED TO BYPASS INTERRUPT VECTOR TABLE 
ORG 0003H          //ISR(INTERRUPT SERVICE ROUTINE) CODE
		CPL P1.4  // COMPLIMENTING VALUE OF PIN P1.4
		RETI      // RETURN

ORG 30H
MAIN: MOV IE,#81H    ; ENABLE EINT0
	  SETB IT0       ; EDGE TRIGGERED INTERRUPT OF TCON REG.
AGAIN:SETB P1.3      // LED BLINKING CODE
	  ACALL Delay
	  CLR P1.3
	  ACALL Delay
	  SJMP AGAIN
		  
		  
DELAY:     MOV R0,#07
     HERE3:MOV R1,#255
     HERE2:MOV R2,#255
     HERE1:DJNZ R2,HERE1
	  DJNZ R1,HERE2
	  DJNZ R0,HERE3
	  
     RET
	 
END
